import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // ── users ─────────────────────────────────────────────────────────────────
  // Single source of truth for identity + app-level profile.
  // Convex stores only what Clerk cannot: theme, interests, onboarding status.
  users: defineTable({
    clerkId: v.string(),           // Clerk `subject` — never store password/tokens
    email: v.string(),
    firstName: v.string(),
    lastName: v.string(),
    imageUrl: v.string(),
    isOnboarded: v.boolean(),
    theme: v.string(),             // "light" | "dark" | "warm"
    interests: v.array(v.string()), // e.g. ["AI", "Finance", "Research"] — feed scoping
    fieldOfStudy: v.string(),       // e.g. "Computer Science"
    weeklyBudgetLimit: v.optional(v.number()), // user-set weekly cap
    createdAt: v.string(),
    updatedAt: v.string(),
  }).index("by_clerkId", ["clerkId"]),

  // ── courses ───────────────────────────────────────────────────────────────
  // Academic subjects with embedded timetable schedules.
  // Referenced by tasks, notes, and budget intelligence.
  courses: defineTable({
    userId: v.string(),            // Clerk user ID
    code: v.string(),              // e.g. "CS302"
    name: v.string(),              // e.g. "Operating Systems"
    color: v.string(),             // HSL string for visual tagging
    schedule: v.array(v.object({
      dayOfWeek: v.number(),       // 0 = Sun … 6 = Sat
      startTime: v.string(),       // "09:00"
      endTime: v.string(),         // "10:30"
      room: v.optional(v.string()),
    })),
    createdAt: v.string(),
    updatedAt: v.string(),
  }).index("by_userId", ["userId"]),

  // ── tasks ─────────────────────────────────────────────────────────────────
  // Unified planner: assignments, exams, and general tasks in one table.
  // `type` differentiates them; `courseId` links them to the calendar.
  tasks: defineTable({
    userId: v.string(),
    courseId: v.optional(v.id("courses")), // relation → courses
    title: v.string(),
    description: v.optional(v.string()),
    type: v.string(),              // "assignment" | "exam" | "task"
    dueDate: v.string(),           // ISO 8601
    effortEstimate: v.optional(v.number()), // hours — used for urgency scoring
    isCompleted: v.boolean(),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
  .index("by_userId", ["userId"])
  .index("by_courseId", ["courseId"]),

  // ── budgetEntries ─────────────────────────────────────────────────────────
  // Date-scoped entries so budget pacing can be cross-referenced
  // against the academic calendar (exam weeks, etc.).
  budgetEntries: defineTable({
    userId: v.string(),
    amount: v.number(),            // positive decimal
    category: v.string(),          // "Food"|"Travel"|"Essentials"|"Entertainment"|"Other"
    description: v.optional(v.string()),
    date: v.string(),              // "YYYY-MM-DD" — enables week-range queries
    createdAt: v.string(),
    updatedAt: v.string(),
  })
  .index("by_userId", ["userId"])
  .index("by_userId_and_date", ["userId", "date"]),

  // ── notes ─────────────────────────────────────────────────────────────────
  // AI-generated study notes and flashcards.
  // `status` enables the pending/processing UI state while Claude runs.
  // `courseId` links notes to the planner for smart suggestions.
  notes: defineTable({
    userId: v.string(),
    courseId: v.optional(v.id("courses")), // relation → courses
    title: v.string(),
    sourceUrl: v.optional(v.string()),  // PDF URL or YouTube link
    sourceType: v.string(),             // "link" | "file"
    summary: v.string(),                // Markdown from Claude — empty while pending
    flashcards: v.array(v.object({
      question: v.string(),
      answer: v.string(),
    })),
    status: v.string(),                 // "pending" | "completed" | "failed"
    errorMessage: v.optional(v.string()),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
  .index("by_userId", ["userId"])
  .index("by_courseId", ["courseId"]),

  // ── weeklySummaries ───────────────────────────────────────────────────────
  // Cross-feature intelligence output: one document per user per week.
  // Generated by a Convex scheduled action — never computed live on load.
  weeklySummaries: defineTable({
    userId: v.string(),
    weekStartDate: v.string(),          // "YYYY-MM-DD" Monday of that week
    budgetInsight: v.string(),          // e.g. "Food at 78% of budget with 4 days left"
    plannerInsight: v.string(),         // e.g. "Two exams this week — heavy load"
    feedItems: v.array(v.object({
      title: v.string(),
      description: v.string(),
      url: v.optional(v.string()),
      category: v.string(),             // "Internship" | "Industry News" | "Academic Tip"
      source: v.optional(v.string()),
    })),
    status: v.string(),                 // "pending" | "completed" | "failed"
    createdAt: v.string(),
  })
  .index("by_userId", ["userId"])
  .index("by_userId_and_week", ["userId", "weekStartDate"]),
});
